config/routes.rb
Rails.application.routes.draw do
  
  get 'about_us', :to => 'infos#about_us'
  get 'terms_and_conditions', :to => 'infos#terms'
  get 'delivery_pricing', :to => 'infos#delivery_pricing'
  get 'job_app_terms_conditions', :to => 'infos#job_app_terms_conditions'
  get 'contact_us', :to => 'tickets#new'
  get 'apply_for_job', :to => 'jobs_applications#new'
  #get 'loaderio-5fff137063d23362ea7c8793a61bad99', :to => 'home#loaderio' 
  get '/en/register' => redirect('/')

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :addresses do
    collection do
      post 'set_primary'
    end
  end

  resources :categories
  get 'category/add'
  
  get '/search', :to => 'search#index', :as => 'search_page'

  resources :room_messages
  resources :rooms do
    collection do
      post 'contact_seller'
    end
  end

  resources :jobs_applications

  resources :notifications
  resources :products
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', omniauth_callbacks: 'users/omniauth_callbacks' }, path: '', path_names: { sign_in: "login", sign_out: "logout" }
  root "home#index"

  resource :products do
    collection do
      post 'mark_as_sold'
      post 'unfollow'
    end
  end

  resource :notifications do
    collection do
      post 'set_message_read'
      post 'set_notif_read'
      post 'email_subscription'
    end
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    post 'create_source', to: 'checkout#create_source', as: 'checkout_create_source'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    post 'source_charge', to: 'checkout#source_charge', as: 'checkout_source_charge'
  end

  resources :orders do
    member do
      get :delete
    end
  end
  get 'order_delivery' => "orders#order_delivery"
  post 'order_delivery' => "orders#order_delivery"
  get 'review_order' => "orders#review"
  post 'review_order' => "orders#review"
  get 'submit_order' => "orders#submit_order"
  post 'submit_order' => "orders#submit_order"
  post 'add_to_delivery' => "orders#add_to_delivery"
  post 'remove_from_delivery' => "orders#remove_from_delivery"
  post 'checkout_order' => "orders#checkout"

  post 'confirm_order' => "order_products#confirm_order"
  post 'accept_delivery' => "order_products#accept_delivery"
  post 'reject_delivery' => "order_products#reject_delivery"

  resources :comments
  resources :tickets
  resources :wallets

  as :user do
  	get 'profile', :to => 'users/registrations#edit', :as => :user_root
    get 'listed_product', :to => 'users/registrations#edit_product', :as => :user_product
    get 'shipping_address', :to => 'users/registrations#edit_address', :as => :user_address
    get 'delivery_order', :to => 'users/registrations#edit_delivery', :as => :user_delivery
    get 'applied_job', :to => 'users/registrations#edit_job_application', :as => :user_job_app
    get 'item_order', :to => 'users/registrations#edit_item_order', :as => :user_item_order
    get 'delivery_offer', :to => 'users/registrations#edit_delivery_offer', :as => :user_delivery_offer
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification
  include Mongoid::Document
  include SimpleEnum::Mongoid

  field :name, type: String
  field :created_at, type: DateTime

  as_enum :status, :read => 1, :unread => 0
  as_enum :type, :comment => 1, :order => 2, :delivery => 3

  belongs_to :user
  belongs_to :product, optional: true
  belongs_to :comment, optional: true

  belongs_to :orderer, :class_name => "User", optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_action :authorized_user, except: [:index, :create, :set_notif_read, :set_message_read, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.where(user_id: current_user.id).order(created_at: :desc)
    @notifications.each do |notification|
      if notification.unread?
        notification.update_attribute :status, :read
      end
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  def set_notif_read
    if user_signed_in?
      if current_user.update_attribute :notif_read, true
        render json: "success".to_json
      else
        render json: "failed".to_json
      end
    end
  end

  def set_message_read
    if user_signed_in?
      if current_user.update_attribute :message_read, true
        render json: "success".to_json
      else
        render json: "failed".to_json
      end
    end
  end

  def email_subscription
    if params.her_key?(:email)
      user = User.find_by(email: params[:email])
      if user.receive_email?
        if current_user.update_attribute :receive_email, false
          redirect_to root_url
        else
          redirect_to root_url
        end
      else
        if current_user.update_attribute :receive_email, true
          redirect_to root_url
        else
          redirect_to root_url
        end
      end
    else
      redirect_to root_url
    end
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
    ActionCable.server.broadcast 'web_notifications_channel', notification: @notification.name, count: Notification.all.count
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:name)
    end

    def authorized_user
      if user_signed_in?
        if current_user.role != :admin
          raise ActionController::RoutingError.new('Not Found')
        end
      else
        raise ActionController::RoutingError.new('Not Found')
      end
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<div class="main-content" style="width: 100%;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Notifications</h4>
                        <!-- <div class="card-header-action">
                          <a href="#" class="btn btn-outline-primary" role="button"><i class="fa fa-check"></i> Mark all as read</a>
                        </div> -->
                    </div>
                    <div class="card-body">
                      <% @notifications.each do |notification| %>
                        <% if notification.type == :comment %>
                          <% if notification.product.present? %>
                            <%= link_to product_path(notification.product), style: "text-decoration: none" do %>
                              <div class="alert alert-primary">
                                <i class="fa fa-comment mr-1"></i>
                                <%= notification.name %>
                                <div class="float-right">
                                    <small class="msg_time time"><%= notification.created_at %></small>
                                </div>
                              </div>
                            <% end %>  
                          <% end %>
                        <% elsif notification.type == :order %>
                          <%= link_to contact_seller_rooms_path(seller_id: notification.orderer.id), method: :post, class: "dropdown-item" do %>
                            <div class="alert alert-success">
                              <i class="fa fa-info mr-1"></i>
                              <%= notification.name %>
                              <div class="float-right">
                                  <small class="msg_time time"><%= notification.created_at %></small>
                              </div>
                            </div>
                          <% end %>
                        <% elsif notification.type == :delivery %>
                          <%= link_to contact_seller_rooms_path(seller_id: notification.orderer.id), method: :post, class: "dropdown-item" do %>
                            <div class="alert alert-info">
                              <i class="fa fa-user mr-1"></i>
                              <%= notification.name %>
                              <div class="float-right">
                                  <small class="msg_time time"><%= notification.created_at %></small>
                              </div>
                            </div>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/notifications/index.zh-CN.html.erb
<div class="main-content" style="width: 100%;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>通知列表</h4>
                        <!-- <div class="card-header-action">
                          <a href="#" class="btn btn-outline-primary" role="button"><i class="fa fa-check"></i> Mark all as read</a>
                        </div> -->
                    </div>
                    <div class="card-body">
                      <% @notifications.each do |notification| %>
                        <% if notification.type == :comment %>
                          <% if notification.product.present? %>
                            <%= link_to product_path(notification.product), style: "text-decoration: none" do %>
                              <div class="alert alert-primary">
                                <i class="fa fa-comment mr-1"></i>
                                <%= notification.name %>
                                <div class="float-right">
                                    <small class="msg_time time"><%= notification.created_at %></small>
                                </div>
                              </div>
                            <% end %>  
                          <% end %>
                        <% elsif notification.type == :order %>
                          <%= link_to contact_seller_rooms_path(seller_id: notification.orderer.id), method: :post, class: "dropdown-item" do %>
                            <div class="alert alert-success">
                              <i class="fa fa-info mr-1"></i>
                              <%= notification.name %>
                              <div class="float-right">
                                  <small class="msg_time time"><%= notification.created_at %></small>
                              </div>
                            </div>
                          <% end %>
                        <% elsif notification.type == :delivery %>
                          <%= link_to contact_seller_rooms_path(seller_id: notification.orderer.id), method: :post, class: "dropdown-item" do %>
                            <div class="alert alert-info">
                              <i class="fa fa-user mr-1"></i>
                              <%= notification.name %>
                              <div class="float-right">
                                  <small class="msg_time time"><%= notification.created_at %></small>
                              </div>
                            </div>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


app/views/notifications/new.html.erb
<div class="main-content">
	<h1>New Notification</h1>

	<%= render 'form', notification: @notification %>

	<%= link_to 'Back', notifications_path %>
</div>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @notification.name %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>