config/routes.rb
Rails.application.routes.draw do
  
  get 'about_us', :to => 'infos#about_us'
  get 'terms_and_conditions', :to => 'infos#terms'
  get 'delivery_pricing', :to => 'infos#delivery_pricing'
  get 'job_app_terms_conditions', :to => 'infos#job_app_terms_conditions'
  get 'contact_us', :to => 'tickets#new'
  get 'apply_for_job', :to => 'jobs_applications#new'
  #get 'loaderio-5fff137063d23362ea7c8793a61bad99', :to => 'home#loaderio' 
  get '/en/register' => redirect('/')

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :addresses do
    collection do
      post 'set_primary'
    end
  end

  resources :categories
  get 'category/add'
  
  get '/search', :to => 'search#index', :as => 'search_page'

  resources :room_messages
  resources :rooms do
    collection do
      post 'contact_seller'
    end
  end

  resources :jobs_applications

  resources :notifications
  resources :products
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', omniauth_callbacks: 'users/omniauth_callbacks' }, path: '', path_names: { sign_in: "login", sign_out: "logout" }
  root "home#index"

  resource :products do
    collection do
      post 'mark_as_sold'
      post 'unfollow'
    end
  end

  resource :notifications do
    collection do
      post 'set_message_read'
      post 'set_notif_read'
      post 'email_subscription'
    end
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    post 'create_source', to: 'checkout#create_source', as: 'checkout_create_source'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    post 'source_charge', to: 'checkout#source_charge', as: 'checkout_source_charge'
  end

  resources :orders do
    member do
      get :delete
    end
  end
  get 'order_delivery' => "orders#order_delivery"
  post 'order_delivery' => "orders#order_delivery"
  get 'review_order' => "orders#review"
  post 'review_order' => "orders#review"
  get 'submit_order' => "orders#submit_order"
  post 'submit_order' => "orders#submit_order"
  post 'add_to_delivery' => "orders#add_to_delivery"
  post 'remove_from_delivery' => "orders#remove_from_delivery"
  post 'checkout_order' => "orders#checkout"

  post 'confirm_order' => "order_products#confirm_order"
  post 'accept_delivery' => "order_products#accept_delivery"
  post 'reject_delivery' => "order_products#reject_delivery"

  resources :comments
  resources :tickets
  resources :wallets

  as :user do
  	get 'profile', :to => 'users/registrations#edit', :as => :user_root
    get 'listed_product', :to => 'users/registrations#edit_product', :as => :user_product
    get 'shipping_address', :to => 'users/registrations#edit_address', :as => :user_address
    get 'delivery_order', :to => 'users/registrations#edit_delivery', :as => :user_delivery
    get 'applied_job', :to => 'users/registrations#edit_job_application', :as => :user_job_app
    get 'item_order', :to => 'users/registrations#edit_item_order', :as => :user_item_order
    get 'delivery_offer', :to => 'users/registrations#edit_delivery_offer', :as => :user_delivery_offer
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@delivery = Order.new
		@recentproducts = Product.status(1).order(created_at: :desc).limit(18)
		@freeproducts = Product.status(1).where(price: 0).order(created_at: :desc).limit(18)

		@electronics = Product.limit(8).order(created_at: :desc).status(1).full_text_search("Electronics")
		@kitchens = Product.limit(8).order(created_at: :desc).status(1).full_text_search("Kitchens")
		@furnitures = Product.limit(8).order(created_at: :desc).status(1).full_text_search("Furnitures")
	end

	#def loaderio
	#	render :layout => false
	#end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% title "Secondhand Items Platform" %>
<% description "Sell your secondhand items with our website. You can also buy cheap electronics, kitchen appliances, furnitures, and many cheap secondhand items. We can help you deliver items around Hokkaido, Japan" %>
<% keywords "Main, Items, Secondhand, Cheap, Delivery, Sell, Buy, Sapporo, Hokkaido, Japan, Gaijin" %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<%= javascript_include_tag 'sub/owl' %>

<div id="carouselExampleIndicators" class="carousel slide mb-n5" data-ride="carousel" style="position: relative; margin-top: 70px;">
    <div class="carousel-inner">
        <!-- <div class="carousel-item active" style="padding: 0px; margin: 0px;">
            <div class="row" style="padding: 0px; margin: 0px;">
                <div class="col-4" style="padding: 0px; margin: 0px;">
                    <a href="<%= new_jobs_application_path(jobtype: "appdev") %>">
                        <%= image_tag "banner/jobbanner1.jpg", class: "w-100", alt: "App Dev Promo" %>
                    </a>
                </div>
                <div class="col-4" style="padding: 0px; margin: 0px;">
                    <a href="<%= new_jobs_application_path(jobtype: "convstaff") %>">
                        <%= image_tag "banner/jobbanner2.jpg", class: "w-100", alt: "App Dev Promo" %>
                    </a>
                </div>
                <div class="col-4" style="padding: 0px; margin: 0px;">
                    <a href="<%= new_jobs_application_path(jobtype: "bedmaking") %>">
                        <%= image_tag "banner/jobbanner3.jpg", class: "w-100", alt: "App Dev Promo" %>
                    </a>
                </div>
            </div>
        </div> -->
        <a href="<%= order_delivery_url %>" class="carousel-item active">
            <%= image_tag "banner/delivery1.png", class: "w-100", alt: "Delivery Promo" %>
        </a>
        <a href="<%= new_product_path %>" class="carousel-item" onclick="<%= new_product_path %>">
            <%= image_tag "cover2.jpg", class: "w-100", alt: "Item Promo" %>
        </a>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="row" style="position: relative; margin-top: 48px; margin-right: 0px; margin-left:0px;">
    <span style="position: absolute; right: 28px; bottom: 14px; z-index: 10;">
        <%= link_to search_page_path(:sortby => 3, :status => 1), style: "color: white" do %>
            See More <i class="fas fa-chevron-right"></i>
        <% end %>
    </span>
    <div class="card" style="margin-bottom: 0px;">
        <div class="card-body" style="background-color: #F17022; padding-top: 10px; padding-bottom: 10px;">
            <div class="card-title text-center" style="margin-bottom: 0px;">
                <%= link_to search_page_path(:sortby => 3, :status => 1), style: "color: white" do %>
                    <h4 style="color: white; margin: 0px;">Recently Added Items</h4>
                <% end %>
            </div>
            <div class="owl-carousel owl-theme" id="home-products-carousel">
                <% if @recentproducts.count > 0 %>
                    <% @recentproducts.each do |rproduct| %>
                        <%= render 'common/rproduct_price_card', rproduct: rproduct %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div class="main-content mt-n5" style="width: 100%; padding-top: 70px;">
    <div class="container-fluid">
        <% if !browser.device.mobile? %>
            <div class="row d-none d-md-block" style="padding-left: 100px; padding-right: 100px;">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h2><center>Electronics</center></h2>
                    <span style="position: absolute; right: 50px; top: 10px;"><%= link_to search_page_path(:categoryname => "Electronics", :sortby => 3) do %>
                        <h4>See More <i class="fas fa-chevron-right"></i></h4>
                    <% end %></span>
                    <div class="row">
                        <% if @electronics.count > 0 %>
                            <% @electronics.each do |product| %>
                                <%= render 'common/product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if browser.device.mobile? %>
            <div class="row d-md-none pl-3 pr-3">
                <div class="card shadow pt-3 col-lg-12 col-md-12 col-sm-12">
                    <h5 style="margin-top: 10px; text-align: left;">Electronics</h2>
                    <span style="position: absolute; right: 15px; top: 30px;"><%= link_to search_page_path(:categoryname => "Electronics", :sortby => 3) do %>
                        See More <i class="fas fa-chevron-right"></i>
                    <% end %></span>
                    <hr>
                    <div class="row" style="display: flex; overflow-x: auto; overflow-y: hidden; flex-wrap: nowrap; margin-left: 0px; margin-right: 0px;">
                        <% if @electronics.count > 0 %>
                            <% @electronics.each do |product| %>
                                <%= render 'common/sm_product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if !browser.device.mobile? %>
            <div class="row d-none d-md-block" style="padding-left: 100px; padding-right: 100px;">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h2><center>Furnitures</center></h2>
                    <span style="position: absolute; right: 50px; top: 10px;"><%= link_to search_page_path(:categoryname => "Furnitures", :sortby => 3) do %>
                        <h4>See More <i class="fas fa-chevron-right"></i></h4>
                    <% end %></span>
                    <div class="row">
                        <% if @furnitures.count > 0 %>
                            <% @furnitures.each do |product| %>
                                <%= render 'common/product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if browser.device.mobile? %>
            <div class="row d-md-none pl-3 pr-3">
                <div class="card shadow pt-3 col-lg-12 col-md-12 col-sm-12">
                    <h5 style="margin-top: 10px; text-align: left;">Furnitures</h2>
                    <span style="position: absolute; right: 15px; top: 30px;"><%= link_to search_page_path(:categoryname => "Furnitures", :sortby => 3) do %>
                        See More <i class="fas fa-chevron-right"></i>
                    <% end %></span>
                    <hr>
                    <div class="row" style="display: flex; overflow-x: auto; flex-wrap: nowrap; margin-left: 0px; margin-right: 0px;">
                        <% if @furnitures.count > 0 %>
                            <% @furnitures.each do |product| %>
                                <%= render 'common/sm_product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if !browser.device.mobile? %>
            <div class="row d-none d-md-block" style="padding-left: 100px; padding-right: 100px;">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h2><center>Kitchens</center></h2>
                    <span style="position: absolute; right: 50px; top: 10px;"><%= link_to search_page_path(:categoryname => "Kitchens", :sortby => 3) do %>
                        <h4>See More <i class="fas fa-chevron-right"></i></h4>
                    <% end %></span>
                    <div class="row">
                        <% if @kitchens.count > 0 %>
                            <% @kitchens.each do |product| %>
                                <%= render 'common/product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if browser.device.mobile? %>
            <div class="row d-md-none pl-3 pr-3">
                <div class="card shadow pt-3 col-lg-12 col-md-12 col-sm-12">
                    <h5 style="margin-top: 10px; text-align: left;">Kitchens</h2>
                    <span style="position: absolute; right: 15px; top: 30px;"><%= link_to search_page_path(:categoryname => "Kitchens", :sortby => 3) do %>
                        See More <i class="fas fa-chevron-right"></i>
                    <% end %></span>
                    <hr>
                    <div class="row" style="display: flex; overflow-x: auto; flex-wrap: nowrap; margin-left: 0px; margin-right: 0px;">
                        <% if @kitchens.count > 0 %>
                            <% @kitchens.each do |product| %>
                                <%= render 'common/sm_product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if user_signed_in? %>
            <span id="signed-in-token" class="d-none">Signed In</span>
        <% else %>
            <span id="signed-in-token" class="d-none"><%= new_user_session_path %></span>
        <% end %>
    </div>
</div>
<div class="row" style="position: relative; margin-top: 10px; margin-right: 0px; margin-left:0px;">
    <span style="position: absolute; right: 28px; bottom: 14px; z-index: 10;">
        <%= link_to search_page_path(:sortby => 3, :maxprice => 0, :status => 1), style: "color: white" do %>
            See More <i class="fas fa-chevron-right"></i>
        <% end %>
    </span>
    <div class="card" style="margin-bottom: -10px; box-shadow: 0 0 0 rgba(0, 0, 0, 0);">
        <div class="card-body" style="background-color: #F17022; padding-top: 10px;">
            <div class="card-title text-center" style="margin-bottom: 0px;">
                <%= link_to search_page_path(:sortby => 3, :maxprice => 0, :status => 1), style: "color: white" do %>
                    <h4 style="color: white; margin: 0px;">Free Items</h4>
                <% end %>
            </div>
            <div class="owl-carousel owl-theme" id="free-products-carousel">
                <% if @freeproducts.count > 0 %>
                    <% @freeproducts.each do |rproduct| %>
                        <%= render 'common/rproduct_price_card', rproduct: rproduct %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/home/index.zh-CN.html.erb
<% title "Secondhand Items Platform" %>
<% description "Secondhand Items Main Page." %>
<% keywords "Main, Items, Secondhand, Cheap" %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<%= javascript_include_tag 'sub/owl' %>

<div id="carouselExampleIndicators" class="carousel slide mb-n5" data-ride="carousel" style="position: relative; margin-top: 70px;">
    <div class="carousel-inner">
        <!-- <div class="carousel-item active">
            <div class="row" style="padding: 0px; margin: 0px;">
                <div class="col-sm-4" style="padding: 0px; margin: 0px;">
                    <a href="<%= new_jobs_application_path(jobtype: "appdev") %>">
                        <%= image_tag "banner/jobbanner1.jpg", class: "w-100", alt: "App Dev Promo" %>
                    </a>
                </div>
                <div class="col-sm-4" style="padding: 0px; margin: 0px;">
                    <a href="<%= new_jobs_application_path(jobtype: "convstaff") %>">
                        <%= image_tag "banner/jobbanner2.jpg", class: "w-100", alt: "App Dev Promo" %>
                    </a>
                </div>
                <div class="col-sm-4" style="padding: 0px; margin: 0px;">
                    <a href="<%= new_jobs_application_path(jobtype: "bedmaking") %>">
                        <%= image_tag "banner/jobbanner3.jpg", class: "w-100", alt: "App Dev Promo" %>
                    </a>
                </div>
            </div>
        </div> -->
        <a href="<%= order_delivery_url %>" class="carousel-item active">
            <%= image_tag "banner/delivery1-zh.png", class: "w-100", alt: "Delivery Promo" %>
        </a>
        <a href="<%= new_product_path %>" class="carousel-item" onclick="<%= new_product_path %>">
            <%= image_tag "cover2.jpg", class: "w-100", alt: "Item Promo" %>
        </a>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">上一页</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">下一页</span>
    </a>
</div>
<div class="row" style="position: relative; margin-top: 48px; margin-right: 0px; margin-left:0px;">
    <span style="position: absolute; right: 28px; bottom: 14px; z-index: 10;">
        <%= link_to search_page_path(:sortby => 3, :status => 1), style: "color: white" do %>
            查看更多 <i class="fas fa-chevron-right"></i>
        <% end %>
    </span>
    <div class="card" style="margin-bottom: 0px;">
        <div class="card-body" style="background-color: #F17022; padding-top: 10px; padding-bottom: 10px;">
            <div class="card-title text-center" style="margin-bottom: 0px;">
                <%= link_to search_page_path(:sortby => 3, :status => 1), style: "color: white" do %>
                    <h4 style="color: white; margin: 0px;">最近添加的商品</h4>
                <% end %>
            </div>
            <div class="owl-carousel owl-theme" id="home-products-carousel">
                <% if @recentproducts.count > 0 %>
                    <% @recentproducts.each do |rproduct| %>
                        <%= render 'common/rproduct_price_card', rproduct: rproduct %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div class="main-content mt-n5" style="width: 100%; padding-top: 70px;">
    <div class="container-fluid">
        <% if !browser.device.mobile? %>
            <div class="row d-none d-md-block">
                <div class="col-lg-12 col-md-12 col-sm-12" style="padding-left: 50px; padding-right: 50px;">
                    <h2><center>电子用品</center></h2>
                    <span style="position: absolute; right: 50px; top: 10px;"><%= link_to search_page_path(:categoryname => "电子用品", :sortby => 3) do %>
                        <h4>查看更多 <i class="fas fa-chevron-right"></i></h4>
                    <% end %></span>
                    <div class="row">
                        <% if @electronics.count > 0 %>
                            <% @electronics.each do |product| %>
                                <%= render 'common/product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if browser.device.mobile? %>
            <div class="row d-md-none pl-3 pr-3">
                <div class="card shadow pt-3 col-lg-12 col-md-12 col-sm-12">
                    <h5 style="margin-top: 10px; text-align: left;">电子用品</h2>
                    <span style="position: absolute; right: 15px; top: 30px;"><%= link_to search_page_path(:categoryname => "电子用品", :sortby => 3) do %>
                        查看更多 <i class="fas fa-chevron-right"></i>
                    <% end %></span>
                    <hr>
                    <div class="row" style="display: flex; overflow-x: auto; overflow-y: hidden; flex-wrap: nowrap; margin-left: 0px; margin-right: 0px;">
                        <% if @electronics.count > 0 %>
                            <% @electronics.each do |product| %>
                                <%= render 'common/sm_product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if !browser.device.mobile? %>
            <div class="row d-none d-md-block">
                <div class="col-lg-12 col-md-12 col-sm-12" style="padding-left: 50px; padding-right: 50px;">
                    <h2><center>家具</center></h2>
                    <span style="position: absolute; right: 50px; top: 10px;"><%= link_to search_page_path(:categoryname => "家具", :sortby => 3) do %>
                        <h4>查看更多 <i class="fas fa-chevron-right"></i></h4>
                    <% end %></span>
                    <div class="row">
                        <% if @furnitures.count > 0 %>
                            <% @furnitures.each do |product| %>
                                <%= render 'common/product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if browser.device.mobile? %>
            <div class="row d-md-none pl-3 pr-3">
                <div class="card shadow pt-3 col-lg-12 col-md-12 col-sm-12">
                    <h5 style="margin-top: 10px; text-align: left;">家具</h2>
                    <span style="position: absolute; right: 15px; top: 30px;"><%= link_to search_page_path(:categoryname => "家具", :sortby => 3) do %>
                        查看更多 <i class="fas fa-chevron-right"></i>
                    <% end %></span>
                    <hr>
                    <div class="row" style="display: flex; overflow-x: auto; flex-wrap: nowrap; margin-left: 0px; margin-right: 0px;">
                        <% if @furnitures.count > 0 %>
                            <% @furnitures.each do |product| %>
                                <%= render 'common/sm_product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if !browser.device.mobile? %>
            <div class="row d-none d-md-block">
                <div class="col-lg-12 col-md-12 col-sm-12" style="padding-left: 50px; padding-right: 50px;">
                    <h2><center>厨房</center></h2>
                    <span style="position: absolute; right: 50px; top: 10px;"><%= link_to search_page_path(:categoryname => "厨房", :sortby => 3) do %>
                        <h4>查看更多 <i class="fas fa-chevron-right"></i></h4>
                    <% end %></span>
                    <div class="row">
                        <% if @kitchens.count > 0 %>
                            <% @kitchens.each do |product| %>
                                <%= render 'common/product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if browser.device.mobile? %>
            <div class="row d-md-none pl-3 pr-3">
                <div class="card shadow pt-3 col-lg-12 col-md-12 col-sm-12">
                    <h5 style="margin-top: 10px; text-align: left;">厨房</h2>
                    <span style="position: absolute; right: 15px; top: 30px;"><%= link_to search_page_path(:categoryname => "厨房", :sortby => 3) do %>
                        查看更多 <i class="fas fa-chevron-right"></i>
                    <% end %></span>
                    <hr>
                    <div class="row" style="display: flex; overflow-x: auto; flex-wrap: nowrap; margin-left: 0px; margin-right: 0px;">
                        <% if @kitchens.count > 0 %>
                            <% @kitchens.each do |product| %>
                                <%= render 'common/sm_product_card', product: product %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <% if user_signed_in? %>
            <span id="signed-in-token" class="d-none">Signed In</span>
        <% else %>
            <span id="signed-in-token" class="d-none"><%= new_user_session_path %></span>
        <% end %>
    </div>
</div>
<div class="row" style="position: relative; margin-top: 10px; margin-right: 0px; margin-left:0px;">
    <span style="position: absolute; right: 28px; bottom: 14px; z-index: 10;">
        <%= link_to search_page_path(:sortby => 3, :maxprice => 0, :status => 1), style: "color: white" do %>
            查看更多 <i class="fas fa-chevron-right"></i>
        <% end %>
    </span>
    <div class="card" style="margin-bottom: -10px; box-shadow: 0 0 0 rgba(0, 0, 0, 0);">
        <div class="card-body" style="background-color: #F17022; padding-top: 10px;">
            <div class="card-title text-center" style="margin-bottom: 0px;">
                <%= link_to search_page_path(:sortby => 3, :maxprice => 0, :status => 1), style: "color: white" do %>
                    <h4 style="color: white; margin: 0px;">免费商品</h4>
                <% end %>
            </div>
            <div class="owl-carousel owl-theme" id="free-products-carousel">
                <% if @freeproducts.count > 0 %>
                    <% @freeproducts.each do |rproduct| %>
                        <%= render 'common/rproduct_price_card', rproduct: rproduct %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/home/loaderio.html.erb
loaderio-5fff137063d23362ea7c8793a61bad99