config/routes.rb
Rails.application.routes.draw do
  
  get 'about_us', :to => 'infos#about_us'
  get 'terms_and_conditions', :to => 'infos#terms'
  get 'delivery_pricing', :to => 'infos#delivery_pricing'
  get 'job_app_terms_conditions', :to => 'infos#job_app_terms_conditions'
  get 'contact_us', :to => 'tickets#new'
  get 'apply_for_job', :to => 'jobs_applications#new'
  #get 'loaderio-5fff137063d23362ea7c8793a61bad99', :to => 'home#loaderio' 
  get '/en/register' => redirect('/')

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :addresses do
    collection do
      post 'set_primary'
    end
  end

  resources :categories
  get 'category/add'
  
  get '/search', :to => 'search#index', :as => 'search_page'

  resources :room_messages
  resources :rooms do
    collection do
      post 'contact_seller'
    end
  end

  resources :jobs_applications

  resources :notifications
  resources :products
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', omniauth_callbacks: 'users/omniauth_callbacks' }, path: '', path_names: { sign_in: "login", sign_out: "logout" }
  root "home#index"

  resource :products do
    collection do
      post 'mark_as_sold'
      post 'unfollow'
    end
  end

  resource :notifications do
    collection do
      post 'set_message_read'
      post 'set_notif_read'
      post 'email_subscription'
    end
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    post 'create_source', to: 'checkout#create_source', as: 'checkout_create_source'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    post 'source_charge', to: 'checkout#source_charge', as: 'checkout_source_charge'
  end

  resources :orders do
    member do
      get :delete
    end
  end
  get 'order_delivery' => "orders#order_delivery"
  post 'order_delivery' => "orders#order_delivery"
  get 'review_order' => "orders#review"
  post 'review_order' => "orders#review"
  get 'submit_order' => "orders#submit_order"
  post 'submit_order' => "orders#submit_order"
  post 'add_to_delivery' => "orders#add_to_delivery"
  post 'remove_from_delivery' => "orders#remove_from_delivery"
  post 'checkout_order' => "orders#checkout"

  post 'confirm_order' => "order_products#confirm_order"
  post 'accept_delivery' => "order_products#accept_delivery"
  post 'reject_delivery' => "order_products#reject_delivery"

  resources :comments
  resources :tickets
  resources :wallets

  as :user do
  	get 'profile', :to => 'users/registrations#edit', :as => :user_root
    get 'listed_product', :to => 'users/registrations#edit_product', :as => :user_product
    get 'shipping_address', :to => 'users/registrations#edit_address', :as => :user_address
    get 'delivery_order', :to => 'users/registrations#edit_delivery', :as => :user_delivery
    get 'applied_job', :to => 'users/registrations#edit_job_application', :as => :user_job_app
    get 'item_order', :to => 'users/registrations#edit_item_order', :as => :user_item_order
    get 'delivery_offer', :to => 'users/registrations#edit_delivery_offer', :as => :user_delivery_offer
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Search
  include SimpleEnum::Mongoid

  field :name, type: String
  field :description, type: String
  field :price, type: Integer
  field :created_at, type: DateTime
  field :updated_at, type: DateTime
  
  field :latitude, type: BigDecimal
  field :longitude, type: BigDecimal
  field :location, type: Array  # [lat,lng]
  index( { location: '2d' }, { min: -180, max: 180 }) # create an special index 
  before_save :fix_location, if: :location_changed? # lat and lng must be in float format
  def fix_location
    self.location = self.location.map(&:to_f)
  end

  field :page_views, type: Integer
  
  as_enum :status, :active => 1, :inactive => 0, :sold => 2
  
  has_many :product_images
  accepts_nested_attributes_for :product_images

  has_many :order_products, inverse_of: :order

  has_and_belongs_to_many :categories
  has_and_belongs_to_many :orders
  belongs_to :user
  has_many :comments
  has_many :tags

  has_and_belongs_to_many :followers, :class_name => "User", :inverse_of => :followed_products

  search_in :name, :price, :created_at, :status_cd, tags: :name, categories: :name

  scope :status, -> (status) { where status_cd: status.to_i }
  scope :user, -> (user) { where user_id: user.to_s }
  scope :minprice, -> (price) { where :price.gte => price }
  scope :maxprice, -> (price) { where :price.lte => price }
  
  scope :sortby, -> (sortby) { 
    if sortby.to_i == 1
      order price: :desc
    elsif sortby.to_i == 2
      order price: :asc
    elsif sortby.to_i == 3
      order created_at: :desc 
    elsif sortby.to_i == 4
      order created_at: :asc
    end           
  }

  scope :pricesort, -> (pricesort) { 
    if pricesort.to_i == 1
      order price: :desc
    elsif pricesort.to_i == 2
      order price: :asc
    end           
  }
  
  scope :datesort, -> (datesort) { 
    if datesort.to_i == 1
      order created_at: :desc 
    elsif datesort.to_i == 2
      order created_at: :asc
    end
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Pagy::Backend
  before_action :redirect_if_no_session, only: [:edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :authorized_user, except: [:show, :new, :mark_as_sold, :create, :update, :destroy, :unfollow]
  invisible_captcha only: [:create]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if params.has_key?(:notification_id)
      notif = Notification.find(id: params[:notification_id])
      if notif.unread?
        notif.update_attribute :status, :read
      end
    end

    @includedcategory = []
    @relatedproducts = []
    @relatedcategory = [] 
    @product.categories.each do |category|
      @relatedcategory.push(category.name)
      category.products.each do |catproduct| 
        if @relatedproducts.count < 8 && catproduct.status != :sold
          @relatedproducts.push(catproduct)
        end
      end
    end

    @userproducts = Product.where(user_id: @product.user.id).status(1).order(created_at: :desc).limit(8)
    @comments = Comment.where(product_id: @product.id).order(created_at: :desc)
    @comment = Comment.new
  end

  # GET /products/new
  def new
    @product = Product.new
    @product_image = @product.product_images.build
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
  end

  def unfollow
    @product = Product.find(params[:id])
    
    if @product.followers.delete(current_user)
      redirect_to @product
    end
  end

  def mark_as_sold
    @product = Product.find(params[:id])
    
    @status = :sold
    if @product.status == :sold
      @status = :active
    end

    @product.status = @status
    @product.updated_at = DateTime.now

    respond_to do |format|
      if @product.update
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render json: "success".to_json }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.status = :active
    @product.created_at = DateTime.now
    @product.updated_at = DateTime.now
    
    current_user.products << @product
    current_user.update

    if params.has_key?(:categories)
      categories = params[:categories]
      categories.each do |category|
        cat = Category.find(category)
        @product.categories << cat
        cat.products << @product
        cat.update
      end
    end

    #respond_to do |format|
    if @product.save
      if params[:product_images].present?
        params[:product_images]['image'].each do |i|
          @product_image = @product.product_images.create!(:image => i, :product_id => @product.id)
        end
        #render "crop"
        redirect_to @product, notice: 'Product was successfully created.'
      else
        redirect_to @product, notice: 'Product was successfully created.'
      end
      #format.html { redirect_to @product, notice: 'Product was successfully created.' }
      #format.json { render :show, status: :created, location: @product }
    else
      render :new
      #format.json { render json: @product.errors, status: :unprocessable_entity }
    end
    #end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    @product.updated_at = DateTime.now

    if params[:product].has_key?(:categories)
      categories = params[:product][:categories]
      categories.each do |category|
        if !category.blank?
          cat = Category.find(category)
          @product.categories << cat
        end
      end
    end

    #respond_to do |format|
      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.'
        #format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        #format.json { render :show, status: :ok, location: @product }
      else
        render :edit
        #format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    #end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to user_product_path, notice: 'Product was successfully destroyed.' }
      format.json { render json: "success".to_json }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :created_at, :updated_at, :latitude, :longitude, :categories, 
                                      product_images_attributes: [:id, :product_id, :image, :crop_x, :crop_y, :crop_w, :crop_h])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end

    def redirect_if_no_session
      if !user_signed_in?
        redirect_to root_url
      end
    end

    def authorized_user
      if user_signed_in?
        if current_user.role != :admin
          raise ActionController::RoutingError.new('Not Found')
        end
      else
        raise ActionController::RoutingError.new('Not Found')
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_edit_modal.html.erb
<div class="modal fade" id="Modal<%= p.id %>" tabindex="-1" role="dialog" aria-labelledby="<%= p.id %>ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="<%= p.id %>ModalLabel">Edit Product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
              <div class="row">
                <%= form_with(model: p, local: true, class: "needs-validation") do |form| %>
                  <% if p.errors.any? %>
                    <div id="error_explanation">
                        <h2><%= pluralize(p.errors.count, "error") %> prohibited this product from being saved:</h2>

                        <ul>
                        <% p.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                    </div>
                  <% end %>

                  <div class="col-md-6 mb-3">
                    <div class="form-group form-inline">
                      <%= form.label :name %>
                      <%= form.text_field :name, class: "form-control", style: "width: 300px;", required: true %>
                      <div class="invalid-feedback">
                        Valid first name is required.
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <div class="form-group form-inline">
                      <%= form.label :categories %>
                      <%= form.select :categories, options_from_collection_for_select(Category.all, "id", "name", {:selected => p.category_ids}), {}, { multiple: true, class: "multiselect2 form-control", style: "width: 300px;" } %>
                      <div class="invalid-feedback">
                        Valid category is required.
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <div class="form-group form-inline">
                      <%= form.label :price %>
                      <%= form.number_field :price, class: "form-control", style: "width: 300px;" %>
                      <div class="invalid-feedback">
                        Valid category is required.
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12 mb-3">
                    <div class="form-group form-inline">
                      <%= form.label :description, "Item Condition" %>
                      <div class="col-md-12 mb-3">
                        <%= form.cktext_area :description, class: "form-control", cols: 40, style: "padding: 0px;" %>
                      </div>
                      <div class="invalid-feedback">
                        Valid category is required.
                      </div>
                    </div>
                  </div>
                <div class="card-footer text-left">
                    <%= form.submit "Save", class: "btn btn-lg btn-primary" %>
                </div>
          </div>
          
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/products/_edit_modal.zh-CN.html.erb
<div class="modal fade" id="Modal<%= p.id %>" tabindex="-1" role="dialog" aria-labelledby="<%= p.id %>ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="<%= p.id %>ModalLabel">Edit Product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
              <div class="row">
                <%= form_with(model: p, local: true, class: "needs-validation") do |form| %>
                  <% if p.errors.any? %>
                    <div id="error_explanation">
                        <h2><%= pluralize(p.errors.count, "error") %> prohibited this product from being saved:</h2>

                        <ul>
                        <% p.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                    </div>
                  <% end %>

                  <div class="col-md-6 mb-3">
                    <div class="form-group form-inline">
                      <%= form.label :name, "姓名" %>
                      <%= form.text_field :name, class: "form-control", style: "width: 300px;", required: true %>
                      <div class="invalid-feedback">
                        Valid first name is required.
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <div class="form-group form-inline">
                      <%= form.label :categories, "商品分类" %>
                      <%= form.select :categories, options_from_collection_for_select(Category.all, "id", "name", {:selected => p.category_ids}), {}, { multiple: true, class: "multiselect2 form-control", style: "width: 300px;" } %>
                      <div class="invalid-feedback">
                        Valid category is required.
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <div class="form-group form-inline">
                      <%= form.label :price, "价格" %>
                      <%= form.number_field :price, class: "form-control", style: "width: 300px;" %>
                      <div class="invalid-feedback">
                        Valid category is required.
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12 mb-3">
                    <div class="form-group form-inline">
                      <%= form.label :description, "商品状况" %>
                      <div class="col-md-12 mb-3">
                        <%= form.cktext_area :description, class: "form-control", cols: 40, style: "padding: 0px;" %>
                      </div>
                      <div class="invalid-feedback">
                        Valid category is required.
                      </div>
                    </div>
                  </div>
                <div class="card-footer text-left">
                    <%= form.submit "保存", class: "btn btn-lg btn-primary" %>
                </div>
          </div>
          
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.text_field :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.time_select :updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_location_modal.html.erb
<div class="modal fade" id="locationModal" tabindex="-1" role="dialog" aria-labelledby="locationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="locationModalLabel">Item's Location</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
              <div class="row">
                <div class="mapouter">
                  <div class="gmap_canvas">
                    <iframe width="100%" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=<%= p.latitude %>,<%= p.longitude %>&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    </div>
                    <style>.mapouter{position:relative;text-align:right;height:500px;width:100%;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:100%;}
                    </style>
                </div>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/products/_location_modal.zh-CN.html.erb
<div class="modal fade" id="locationModal" tabindex="-1" role="dialog" aria-labelledby="locationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="locationModalLabel">商品的位置</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
              <div class="row">
                <div class="mapouter">
                  <div class="gmap_canvas">
                    <iframe width="100%" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=<%= p.latitude %>,<%= p.longitude %>&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    </div>
                    <style>.mapouter{position:relative;text-align:right;height:500px;width:100%;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:100%;}
                    </style>
                </div>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/products/_product_form.html.erb
<%= form_with(model: @product, local: true, class: "needs-validation") do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
    <% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group form-inline">
      <%= form.label :name, style: "width: 190px" %>
      <%= form.text_field :name, class: "form-control", placeholder: "Item Name", style: "width: 300px", required: true %>
    </div>
  </div>
  <div class="row">
      <div class="form-group form-inline">
          <label style="width: 190px;">Categories</label>
          <%= select_tag :categories, options_from_collection_for_select(@categories, "id", "name"), { multiple: true, id: "select2", class: "form-control", style: "width: 300px;" } %>
      </div>
  </div>
  <div class="row">
      <div class="form-group form-inline">
          <%= form.label :price, style: "width: 190px" %>
          <div class="input-group">
              <div class="input-group-prepend">
                  <div class="input-group-text">
                      ¥
                  </div>
              </div>
              <%= form.number_field :price, class: "form-control", min: 0, style: "width: 260px", required: true %>
          </div>
      </div>
  </div>
  <div class="row">
      <div class="form-group form-inline"> <!--custom-file-->
        <%= form.label :product_images, style: "width: 190px" %> 
        <%= form.file_field :product_images, :multiple => true, name: "product_images[image][]", id: "product-image-upload", class: "form-control", data: { "browse-on-zone-click": true }, required: true %>
      </div>
  </div>
  <div class="row">
      <div class="form-group form-inline"> <!--custom-file-->
          <label style="width: 190px;">Location</label> 
          <input type="text" id="pac-input" class="form-control" placeholder="Input Item's Location Here" style="width: 300px;">
      </div>
  </div>
  <div class="row">
      <div class="form-group form-inline">
          <label style="width: 190px;">Map</label>
          <div id="product-map" style="width: 300px; height: 200px;"></div>
      </div>
      <%= form.hidden_field :latitude, id: "address-lat-2" %>
      <%= form.hidden_field :longitude, id: "address-long-2" %>
  </div>
  <div class="row">
      <div class="form-group form-inline">
          <%= form.label :description, style: "width: 190px" %>
          <%= form.cktext_area :description, id: "product-editor", placeholder: "Add color, conditions, and status of the item", cols: 40, style: "width: 300px", required: true %>
      </div>
  </div>
  <div class="card-footer text-left">
      <%= form.submit "List Item", id: "ckeditor-btn", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/products/crop.html.erb
<div class="main-content" style="width: 100%;">
  <div class="container">
    <div class="card">
      <h5 class="panel-title" style="margin-left: 20px; margin-top: 20px">Crop Images</h3>
      <hr>
      <div class='card-body'>
        <%= form_for @product do |f| %>
          <%= f.fields_for :product_images do |builder| %>
            <div class='col-12 product-image-forms' style="overflow: auto; overflow-y: hidden; margin-left: -25px;">
              <%= image_tag builder.object.image.url, class: "cropbox" %>
              <br>
              <% %w[x y w h].each do |attribute| %>
                <%= builder.hidden_field "crop_#{attribute}", class: "crop_#{attribute}_attr" %>
              <% end %>
            </div>
          <% end %>
          <div class="form-actions">
            <%= f.button :Submit, class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.created_at %></td>
        <td><%= product.updated_at %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>