config/routes.rb
Rails.application.routes.draw do
  
  get 'about_us', :to => 'infos#about_us'
  get 'terms_and_conditions', :to => 'infos#terms'
  get 'delivery_pricing', :to => 'infos#delivery_pricing'
  get 'job_app_terms_conditions', :to => 'infos#job_app_terms_conditions'
  get 'contact_us', :to => 'tickets#new'
  get 'apply_for_job', :to => 'jobs_applications#new'
  #get 'loaderio-5fff137063d23362ea7c8793a61bad99', :to => 'home#loaderio' 
  get '/en/register' => redirect('/')

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :addresses do
    collection do
      post 'set_primary'
    end
  end

  resources :categories
  get 'category/add'
  
  get '/search', :to => 'search#index', :as => 'search_page'

  resources :room_messages
  resources :rooms do
    collection do
      post 'contact_seller'
    end
  end

  resources :jobs_applications

  resources :notifications
  resources :products
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', omniauth_callbacks: 'users/omniauth_callbacks' }, path: '', path_names: { sign_in: "login", sign_out: "logout" }
  root "home#index"

  resource :products do
    collection do
      post 'mark_as_sold'
      post 'unfollow'
    end
  end

  resource :notifications do
    collection do
      post 'set_message_read'
      post 'set_notif_read'
      post 'email_subscription'
    end
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    post 'create_source', to: 'checkout#create_source', as: 'checkout_create_source'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    post 'source_charge', to: 'checkout#source_charge', as: 'checkout_source_charge'
  end

  resources :orders do
    member do
      get :delete
    end
  end
  get 'order_delivery' => "orders#order_delivery"
  post 'order_delivery' => "orders#order_delivery"
  get 'review_order' => "orders#review"
  post 'review_order' => "orders#review"
  get 'submit_order' => "orders#submit_order"
  post 'submit_order' => "orders#submit_order"
  post 'add_to_delivery' => "orders#add_to_delivery"
  post 'remove_from_delivery' => "orders#remove_from_delivery"
  post 'checkout_order' => "orders#checkout"

  post 'confirm_order' => "order_products#confirm_order"
  post 'accept_delivery' => "order_products#accept_delivery"
  post 'reject_delivery' => "order_products#reject_delivery"

  resources :comments
  resources :tickets
  resources :wallets

  as :user do
  	get 'profile', :to => 'users/registrations#edit', :as => :user_root
    get 'listed_product', :to => 'users/registrations#edit_product', :as => :user_product
    get 'shipping_address', :to => 'users/registrations#edit_address', :as => :user_address
    get 'delivery_order', :to => 'users/registrations#edit_delivery', :as => :user_delivery
    get 'applied_job', :to => 'users/registrations#edit_job_application', :as => :user_job_app
    get 'item_order', :to => 'users/registrations#edit_item_order', :as => :user_item_order
    get 'delivery_offer', :to => 'users/registrations#edit_delivery_offer', :as => :user_delivery_offer
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/common/_category.html.erb
<h2><center>Categories</center></h2>
<div class="row">
    <a href="<%= search_page_path(:category => "Electronics") %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="width: 250px; height:100%">
        <div class="card">
            <center>
                <i class="fa fa-plug fa-10x" class="card-img-top" alt="image" style="padding-top: 50px; width: 250px; height: 250px; object-fit: fill;"></i>
            </center>
            <center>
                <h4 class="card-title">Electronics</h4>
            </center>
        </div>
    </a>
    <a href="<%= search_page_path(:category => "White Appliances") %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="width: 250px; height:100%">
        <div class="card">
            <center>
                <i class="fa fa-tablet fa-10x" class="card-img-top" alt="image" style="padding-top: 50px; width: 250px; height: 250px; object-fit: fill;"></i>
            </center>
            <center>
                <h4 class="card-title">White Appliances</h4>
            </center>
        </div>
    </a>
    <a href="<%= search_page_path(:category => "Furnitures") %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="width: 250px; height:100%">
        <div class="card">
            <center>
                <i class="fa fa-couch fa-10x" class="card-img-top" alt="image" style="padding-top: 50px; width: 250px; height: 250px; object-fit: fill;"></i>
            </center>
            <center>
                <h4 class="card-title">Furnitures</h4>
            </center>
        </div>
    </a>
    <a href="<%= search_page_path(:category => "Kitchens") %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="width: 250px; height:100%">
        <div class="card">
            <center>
                <i class="fa fa-utensils fa-10x" class="card-img-top" alt="image" style="padding-top: 50px; width: 250px; height: 250px; object-fit: fill;"></i>
            </center>
            <center>
                <h4 class="card-title">Kitchens</h4>
            </center>
        </div>
    </a>
    <a href="<%= search_page_path(:category => "Books") %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="width: 250px; height:100%">
        <div class="card">
            <center>
                <i class="fa fa-book fa-10x" class="card-img-top" alt="image" style="padding-top: 50px; width: 250px; height: 250px; object-fit: fill;"></i>
            </center>
            <center>
                <h4 class="card-title">Books</h4>
            </center>
        </div>
    </a>
    <a href="<%= search_page_path(:category => "Apparels") %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="width: 250px; height:100%">
        <div class="card">
            <center>
                <i class="fa fa-tshirt fa-10x" class="card-img-top" alt="image" style="padding-top: 50px; width: 250px; height: 250px; object-fit: fill;"></i>
            </center>
            <center>
                <h4 class="card-title">Apparels</h4>
            </center>
        </div>
    </a>
    <a href="<%= search_page_path(:category => "Sports") %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="width: 250px; height:100%">
        <div class="card">
            <center>
                <i class="fa fa-volleyball-ball fa-10x" class="card-img-top" alt="image" style="padding-top: 50px; width: 250px; height: 250px; object-fit: fill;"></i>
            </center>
            <center>
                <h4 class="card-title">Sports</h4>
            </center>
        </div>
    </a>
    <a href="<%= search_page_path(:category => "Miscellaneous") %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="width: 250px; height:100%">
        <div class="card">
            <center>
                <i class="fa fa-ellipsis-h fa-10x" class="card-img-top" alt="image" style="padding-top: 50px; width: 250px; height: 250px; object-fit: fill;"></i>
            </center>
            <center>
                <h4 class="card-title">Miscellaneous</h4>
            </center>
        </div>
    </a>
</div>

app/views/common/_delivery_modal.zh-CN.html.erb
<div class="modal fade" id="deliveryModal" tabindex="-1" role="dialog" aria-labelledby="deliveryModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deliveryModalTitle">Delivery</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="delivery-tab" data-toggle="tab" href="#delivery" role="tab" aria-controls="delivery" aria-selected="true">联系方式与出发地方</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="checkout-delivery-tab" data-toggle="tab" href="#checkout-delivery" role="tab" aria-controls="checkout-delivery" aria-selected="false">终点目的地与结算</a>
          </li>
        </ul>
        <%= form_for delivery, html: { id: "delivery_form" } do |f| %>
          <%= invisible_captcha %>
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="delivery" role="tabpanel" aria-labelledby="delivery-tab">
                <div class="mb-3">
                  <% if current_user.last_name.present? 
                      @fullname = current_user.first_name + " " + current_user.last_name
                    else
                      @fullname = current_user.first_name
                    end
                  %>
                  <%= f.label :name, "名字" %>
                  <%= f.text_field :name, class: "form-control", value: @fullname, required: true %>
                </div>
                <div class="mb-3">
                  <%= f.label :email, "电子邮箱" %>
                  <%= f.email_field :email, class: "form-control", value: current_user.email, placeholder: "Ex. username@example.com", required: true %>
                </div>
                <div class="mb-3">
                  <%= f.label :phone, "电话号码" %>
                  <%= f.text_field :phone, type: "tel", class: "form-control", value: current_user.phone, placeholder: "" %>
                </div>
                <div class="mb-3">
                  <%= f.label :wechat, "微信号" %>
                  <%= f.text_field :wechat, class: "form-control", value: current_user.wechat, placeholder: "" %>
                </div>
              <hr class="mb-4">
              <h5>想搬的东西和地点</h5>
              <h6>从网站的商品</h6>
              <% if delivery.products.count > 0 %>
                <% delivery.products.each do |product| %>
                  <div class="card mb-3" style="padding: 10px;">
                    <a href="<%= product_path(product)%>"><%= product.name %></a>
                    <span>
                      <%= link_to "删除", remove_from_delivery_delivery_path(id: product.id), method: :post, style: "position: absolute; right: 5px; top: 5px;", class: "btn btn-outline-danger" %> 
                    </span>
                  </div>
                <% end %>
              <% else %>
                没有加入网站的的商品。您可以通过点击产品页面上的{添加到运送}添加一个
              <% end %>
              <h6 style="margin-top: 10px;">东西</h6>
              <%= f.fields_for :delivery_items, DeliveryItem.new do |item| %>
                <div class="mb-3">
                  <%= render "deliveries/delivery_item_fields", f: item %>
                </div>
                <div class="mb-3" style="height: 100%">
                  <%= link_to_add_association f, :delivery_items, render_options: { wrapper: 'bootstrap' }, partial: 'deliveries/delivery_item_fields' do %>
                    <button class="btn btn-primary" style="width: 120px">加地址</button>
                  <% end %>
                  *(万一有几个地方)
                </div>
              <% end %>
            </div>
            <div class="tab-pane fade" id="checkout-delivery" role="tabpanel" aria-labelledby="checkout-delivery-tab">
              <b>目的地</b>
              <%= f.fields_for :address do |builder| %>
                <div class="mb-3">
                  <%= builder.label :full_address, "地址" %>
                  <%= builder.text_field :full_address, class: "form-control", placeholder: "Ex. Kita 2-jo, Nishi 1-Chome", required: true %>
                </div>
                <div class="mb-3">
                  <%= builder.label :apartment, "公寓名" %>
                  <%= builder.text_field :apartment, class: "form-control", placeholder: "Ex. Cross Building, 115" %>
                </div>
                <div class="row">
                  <div class="col-md-4 mb-3">
                    <%= builder.label :state, "州" %>
                    <%= builder.select :state, options_for_select(['Hokkaido'], delivery.address.state), {}, { class: "custom-select d-block w-100", required: true } %>
                  </div>
                  <div class="col-md-4 mb-3">
                    <%= builder.label :city, "城市" %>
                    <%= builder.select :city, options_for_select(['Sapporo'], delivery.address.city), {}, { class: "custom-select d-block w-100", required: true } %>
                  </div>
                  <div class="col-md-4 mb-3">
                    <%= builder.label :postal_code, "邮政编码" %>
                    <%= builder.text_field :postal_code, class: "form-control" %>                      
                  </div>
                  <%= builder.hidden_field :user_id, value: current_user.id, required: true %>
                </div>
              <% end %>
              <hr class="mb-4">
              <div class="d-block my-3">
                <h6>支付方式</h6>
                <div class="custom-control custom-radio">
                  <%= f.radio_button :payment_method, 'cod', class: "custom-control-input", :checked => true %> 
                  <%= label :payment_method, '现金付款', class: "custom-control-label" %>
                </div>
              </div>
              <div class="d-block my-3">
                <h6>运送日期</h6>
                <%= f.datetime_local_field :shipping_date, class: "datetimepicker", style: "z-index: 1000;", required: true %><br>
              </div>
              <div class="d-block my-3">
                <h6>价格</h6>
                基本费+950日元/15分(基本费是地方区别)
                <br><b>*<a href="<%= delivery_pricing_url %>" target="_blank">详细的价格和规则请在这里按</a></b>
              </div>
              <hr class="mb-4">
              <%= f.button "结算", type: :submit, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/common/_edit_delivery_modal.html.erb
<div class="modal fade" id="deliveryModal<%= delivery.id %>" tabindex="-1" role="dialog" aria-labelledby="deliveryModal<%= delivery.id %>" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deliveryModalTitle">Delivery</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="edit-delivery-tab-<%= delivery.id %>" data-toggle="tab" href="#edit-delivery-<%= delivery.id %>" role="tab" aria-controls="edit-delivery-<%= delivery.id %>" aria-selected="true">Contact Info and Starting Places</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="edit-checkout-delivery-tab-<%= delivery.id %>" data-toggle="tab" href="#edit-checkout-delivery-<%= delivery.id %>" role="tab" aria-controls="edit-checkout-delivery-<%= delivery.id %>" aria-selected="false">Destination and Checkout</a>
          </li>
        </ul>
        <%= form_for delivery, html: { id: "delivery_form" } do |f| %>
          <%= invisible_captcha %>
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="edit-delivery-<%= delivery.id %>" role="tabpanel" aria-labelledby="edit-delivery-tab-<%= delivery.id %>">
                <div class="mb-3">
                  <% if current_user.last_name.present? 
                      @fullname = current_user.first_name + " " + current_user.last_name
                    else
                      @fullname = current_user.first_name
                    end
                  %>
                  <%= f.label :name %>
                  <%= f.text_field :name, class: "form-control", value: @fullname, required: true %>
                </div>
                <div class="mb-3">
                  <%= f.label :email %>
                  <%= f.email_field :email, class: "form-control", value: current_user.email, placeholder: "Ex. username@example.com", required: true %>
                </div>
                <div class="mb-3">
                  <%= f.label :phone %>
                  <%= f.text_field :phone, type: "tel", class: "form-control", value: current_user.phone, placeholder: "" %>
                </div>
                <div class="mb-3">
                  <%= f.label :wechat, "WeChat ID (If any)" %>
                  <%= f.text_field :wechat, class: "form-control", value: current_user.wechat, placeholder: "" %>
                </div>
              <hr class="mb-4">
              <h5>Items to be Delivered</h5>
              <h6>Items from this Website</h6>
              <% if delivery.products.count > 0 %>
                <% delivery.products.each do |product| %>
                  <div class="card mb-3" style="padding: 10px;">
                    <a href="<%= product_path(product)%>"><%= product.name %></a>
                  </div>
                <% end %>
              <% else %>
                No items from this website added. You can add one by clicking Add to Delivery on product page
              <% end %>
              <h6 style="margin-top: 10px;">Other Items</h6>
              <%= f.fields_for :delivery_items do |item| %>
                <div class="mb-3">
                  <%= render "orders/delivery_item_fields", f: item %>
                </div>
                <div class="mb-3" style="height: 100%">
                  <%= link_to_add_association f, :delivery_items, render_options: { wrapper: 'bootstrap' }, partial: 'orders/delivery_item_fields' do %>
                    <button class="btn btn-primary" style="width: 120px">Add Location</button>
                  <% end %>
                  *In case of multiple places
                </div>
              <% end %>
              
            </div>
            <div class="tab-pane fade" id="edit-checkout-delivery-<%= delivery.id %>" role="tabpanel" aria-labelledby="edit-checkout-delivery-tab-<%= delivery.id %>">
              <b>Destination</b>
              <%= f.fields_for :address do |builder| %>
                <div class="mb-3">
                  <%= builder.label :full_address %>
                  <%= builder.text_field :full_address, class: "form-control", placeholder: "Ex. Kita 14-jo, Nishi 4-Chome", required: true %>
                </div>
                <div class="mb-3">
                  <%= builder.label :apartment, "Apartment and Room Number (Optional)" %>
                  <%= builder.text_field :apartment, class: "form-control", placeholder: "Ex. Fujii Building, 115" %>
                </div>
                <div class="row">
                  <div class="col-md-4 mb-3">
                    <%= builder.label :state %>
                    <%= builder.select :state, options_for_select(['Hokkaido'], delivery.address.state), {}, { class: "custom-select d-block w-100", required: true } %>
                  </div>
                  <div class="col-md-4 mb-3">
                    <%= builder.label :city %>
                    <%= builder.select :city, options_for_select(['Sapporo'], delivery.address.city), {}, { class: "custom-select d-block w-100", required: true } %>
                  </div>
                  <div class="col-md-4 mb-3">
                    <%= builder.label :postal_code %>
                    <%= builder.text_field :postal_code, class: "form-control", required: true %>                      
                  </div>
                  <%= builder.hidden_field :user_id, value: current_user.id, required: true %>
                </div>
              <% end %>
              <hr class="mb-4">
              <div class="d-block my-3">
                <h6>Payment Method</h6>
                <div class="custom-control custom-radio">
                  <%= f.radio_button :payment_method, 'cod', class: "custom-control-input", :checked => true %> 
                  <%= label :payment_method, 'Cash on Delivery', class: "custom-control-label" %>
                </div>
              </div>
              <div class="d-block my-3">
                <h6>Delivery Date</h6>
                <%= f.datetime_local_field :shipping_date, class: "datetimepicker", style: "z-index: 1000;", required: true %><br>
              </div>
              <div class="d-block my-3">
                <h6>Price</h6>
                Basic fee + 950 yen/15 minutes (basic fee differs according to places)
                <br><b>*<a href="<%= delivery_pricing_url %>" target="_blank">Click here for pricing details and terms</a></b>
              </div>
              <hr class="mb-4">
              <%= f.button "Check Out", type: :submit, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/common/_fab_add_product.zh-CN.html.erb
<div id="fabposition">
    <div id="fabcontent">
		<div id="extending-fab" class="extending-fab" data-new-product-path="<%= new_product_path %>">
		    <br>
		    <i class="fas fa-camera" style="color: white; font-size: 24px;"></i>
		    <span id="extending-fab-text" class="hidden" style="margin-left: 5px; margin-top: 7px; color: white;">
		        <h6>出售</h6>
		    </span>
		    <br>
		</div>
	</div>
</div>

app/views/common/_flash_message.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/common/_footer.html.erb
<!-- Footer -->
<footer style="margin-top: 10px;">
	<div class="footer-bottom">
    	<div class="container">
    		<div class="row">
       			<div class="col-md-5 d-none d-sm-block d-md-block justify-content-center footer-copyright">
                	<p>&copy; 2Gaijin.com 2019 by <a href="https://kitalabs.com" target="_blank">KitaLabs, Co. Ltd.</a></p>
                </div>
       			<div class="col-md-7 footer-menu">
                	<nav class="navbar-footer navbar-dark navbar-expand-md">
					    <div class="navbar-collapse" id="navbarNav">
					        <ul class="navbar-footer-nav ml-auto">
					            <li class="nav-item">
					                <a class="nav-link scroll-link" href="<%= about_us_path %>">About Us</a>
					            </li>
					            <li class="nav-item">
					                <a class="nav-link scroll-link" href="<%= contact_us_path %>">Contact Us</a>
					            </li>
					            <li class="nav-item">
					                <a class="nav-link scroll-link" href="<%= terms_and_conditions_path %>">Terms and Policies</a>
					            </li>
					        </ul>
					    </div>
					</nav>
                </div>
       		</div>
    	</div>
    </div>
	<div class="footer-top">
        <div class="container">
        	<div class="row">
        		<div class="col-md-4 col-lg-4 footer-about wow fadeInUp">
        			<center><%= image_tag "2gaijinicon.png", style: "width: 50px; height: auto;" %></center>
                    <p>
        				2Gaijin is our product that helps you sell your items and deliver items right in front of your door
        			</p>
        			<p><a href="http://kitalabs.com">Our Company</a></p>
                </div>
        		<div class="col-md-4 col-lg-4 offset-lg-1 footer-contact wow fadeInDown">
        			<h3>Contact</h3>
                	<p><i class="fas fa-map-marker-alt"></i> Sapporo-shi, Hokkaido, Japan</p>
                	<p><i class="fas fa-phone"></i> Phone: (+81)80-8293-4266</p>
                	<p><i class="fas fa-envelope"></i> Email: <a href="mailto:2gaijin@kitalabs.com">2gaijin@kitalabs.com</a></p>
                </div>
                <div class="col-md-4 col-lg-3 footer-social wow fadeInUp">
                    <h4 style="color: #ffffff">Language</h4>
                    <form>
                        <%= select_tag :locale, options_for_select([["English", :en], ["简体中文", "zh-CN"]], :en), { class: "singleselect2", style: "width: 100%;", onchange: "this.form.submit();" } %>
                    </form>
                	<h4 style="color: #ffffff; margin-top: 15px;">Follow us</h4>
                	<p>
                		<a href="https://www.facebook.com/2gaijin/" target="_blank"><i class="fab fa-facebook"></i></a>
						<a href="mailto:2gaijin@kitalabs.com"><i class="fab fa-google-plus-g"></i></a>
                	</p>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/common/_footer.zh-CN.html.erb
<!-- Footer -->
<footer style="margin-top: 10px;">
	<div class="footer-bottom">
    	<div class="container">
    		<div class="row">
       			<div class="col-md-5 d-none d-sm-block d-md-block justify-content-center footer-copyright">
                	<p>&copy; 2Gaijin.com 2019 by <a href="https://kitalabs.com" target="_blank">KitaLabs, Co. Ltd.</a></p>
                </div>
       			<div class="col-md-7 footer-menu">
                	<nav class="navbar-footer navbar-dark navbar-expand-md">
					    <div class="navbar-collapse" id="navbarNav">
					        <ul class="navbar-footer-nav ml-auto">
					            <li class="nav-item">
					                <a class="nav-link scroll-link" href="<%= about_us_path %>">关于我们</a>
					            </li>
					            <li class="nav-item">
					                <a class="nav-link scroll-link" href="<%= contact_us_path %>">联系我们</a>
					            </li>
					            <li class="nav-item">
					                <a class="nav-link scroll-link" href="<%= terms_and_conditions_path %>">条款和政策</a>
					            </li>
					        </ul>
					    </div>
					</nav>
                </div>
       		</div>
    	</div>
    </div>
	<div class="footer-top">
        <div class="container">
        	<div class="row">
        		<div class="col-md-4 col-lg-4 footer-about wow fadeInUp">
        			<center><%= image_tag "2gaijinicon.png", style: "width: 50px; height: auto;" %></center>
                    <p>
        				我们的产品2Gaijin可以帮助您销售您的物品，并且上门取货。
        			</p>
        			<p><a href="http://kitalabs.com">我们公司</a></p>
                </div>
        		<div class="col-md-4 col-lg-4 offset-lg-1 footer-contact wow fadeInDown">
        			<h3>联系</h3>
                	<p><i class="fas fa-map-marker-alt"></i> 日本北海道札幌市</p>
                	<p><i class="fas fa-phone"></i> 联系电话: (+81)80-8293-4266</p>
                	<p><i class="fas fa-envelope"></i> 电子邮箱: <a href="mailto:2gaijin@kitalabs.com">2gaijin@kitalabs.com</a></p>
                </div>
                <div class="col-md-4 col-lg-3 footer-social wow fadeInUp">
                    <h4 style="color: #ffffff">语言</h4>
                    <form>
                        <%= select_tag :locale, options_for_select([["English", :en], ["简体中文", "zh-CN"]], "zh-CN"), { class: "singleselect2", style: "width: 100%;", onchange: "this.form.submit();" } %>
                    </form>
                	<h4 style="color: #ffffff; margin-top: 15px;">跟着我们</h4>
                	<p>
                		<a href="https://www.facebook.com/2gaijin/" target="_blank"><i class="fab fa-facebook"></i></a>
						<a href="mailto:2gaijin@kitalabs.com"><i class="fab fa-google-plus-g"></i></a>
                	</p>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/common/_product_card.zh-CN.html.erb
<a href="<%= product_path(product) %>" class="col-lg-3 col-md-3 col-sm-3 mx-auto" style="text-decoration: none; width: 250px; height:100%; padding-left: 5px; padding-right: 5px;">
    <div class="card" style="box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.19);">
        <% if product.status == :sold %>
            <div class="ribbon ribbon-top-left"><span>Sold Out</span></div>
        <% end %>
        <% if product.product_images.present? %>
	        <% if product.product_images[0].image.present? %>
                <%= image_tag product.product_images[0].image.url, class: "card-img-top", alt: "image", style: "width: 100%; height: 250px; object-fit: cover;" %>
            <% else %>
                <%= image_tag "products/product-1-500.png", class: "card-img-top", alt: "image", style: "width: 100%; height: 250px; object-fit: cover;" %>
            <% end %>
	    <% else %>
            <%= image_tag "products/product-1-500.png", class: "card-img-top", alt: "image", style: "width: 100%; height: 250px; object-fit: cover;" %>
        <% end %>
        
        <div class="card-body" style="height: 110px;">
            <span class="card-text"><h5 class="card-title"><%= product.name %></h5></span>
            <var class="price h5 text-warning" style="position: absolute; bottom: 5px; left: 20px;">
                <% if product.price == 0 %>
                    <span class="currency">免费</span>
                <% else %> 
                    <span class="currency">&#165;</span><span class="num"><%= product.price %></span>
                <% end %>
            </var>
        </div>
    </div>
</a>